### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by Fot0n** [statikbe/laravel-filament-chained-translation-manager#11]
Hello! Is it possible to hope for the addition of Laravel 10 support?

**Comment by kristofser** [comment]
Hi @Fot0n 
This is planned to be released on Monday.

**Comment by kristofser** [comment]
@Fot0n Release has been made. Version 1.1.0 will work on Laravel 10

**Comment by rikiless** [comment]
Can I upgrade to Laravel 10 on Filament V2? I have latest version of Filament v2.17.14 and installing this package throwed me an error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires statikbe/laravel-filament-chained-translation-manager ^1.1 -> satisfiable by statikbe/laravel-filament-chained-translation-manager[1.1.0].
    - statikbe/laravel-filament-chained-translation-manager 1.1.0 requires illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require statikbe/laravel-filament-chained-translation-manager:*" to figure out if any version is installable, or "composer require statikbe/laravel-filament-chained-translation-manager:^2.1" if you know which you need.
```

**Comment by kristofser** [comment]
@rikiless 
I've set up a test project with the following requirements:
```
"php": "^8.1",
"filament/filament": "^2.17",
"statikbe/laravel-filament-chained-translation-manager": "^1.1",
"laravel/framework": "^10.0"
```

This seems to work as intended.
Could you send me your composer file so I could check it out?

**Comment by rikiless** [comment]
I didn't know that it's safe to upgrade Laravel 10 on Filament V2. Instead of this I installed `"statikbe/laravel-filament-chained-translation-manager": "1.0.1"` and everything works fine. I will wait when they officially bump version to L10 (in V2 or V3).

Anyway high quality translation package/plugin for FilamentPHP. Thanks!
