### ISSUE TITLE
Check filament translation file from vendor, ignore already published vendor translation

### ISSUE THREAD

**Issue by valpuia** [statikbe/laravel-filament-chained-translation-manager#15]
This package is very useful and great.. Love the Idea and how it represent. But have one issue..

Before I use this package, I already publish filament translation file from vendor, later I used this package, but it override whatever I changed in `published vendor translation`.
Example: I changed 'Save Changes' to 'Update', but after using this it comes back to 'Save changes' again, and can update data from `Translation Manager` again, but it make double work..

Not sure whether this is correct.. but whatever customization i created for translation is replaced again.. the published vendor file should be respect and used if it is published (in my opinion)

**Comment by sten** [comment]
@Valpuia Thanks for the bug report. We have investigated the issue and it indeed was a bug. We fixed it in the base package, see https://github.com/statikbe/laravel-chained-translator/pull/6 

Thanks, @WoutDeBoeck for the fix!

If you do a `composer upgrade` the new version (2.2.1) of `statikbe/laravel-chained-translator` should be installed with the fix.
