### ISSUE TITLE
Disabled icon components

### ISSUE THREAD

**Issue by gsusanj** [statikbe/laravel-filament-chained-translation-manager#32]
I have disabled the Icon components within the Blade-icons configuration (as I am using Font Awesome icons, there are a lot of them and it noticeably slowed down the website).

At first, this came up as an issue as in your views you use the blade ui icon components directly. I have fixed this by publishing your views and overriding the components with @svg version. 

The website works fine, but I am unable to run view:cache, as it always throw an error in your views because of above issue.
I do not know how exactly the view:cache works but it seems that it references your files instead of my overrides, as its there where the error is thrown.

Using:

- php 8.1 and php 8.2
- Laravel 10.33.0
- Filament 3.0.102
- Blade-fontawesome 2.4.1
- Version 3.1.2 of your package

I believe this issue can be avoided by replacing the <x-heroicon calls with @svg directives

**Comment by sten** [comment]
Thanks for reporting this. Probably it would be better to solve this by using the new filament icon component and use icon aliases so anyone can override the alias. See https://filamentphp.com/docs/3.x/support/icons

The earliest I can look into this will be after January 15th. I am currently on holidays. PRs are welcome!

**Comment by meeftah** [comment]
is there any updates?

**Comment by sten** [comment]
@meeftah I finally updated the icons so you can configure your own icon sets. I hope this is still of use to anyone.

**Comment by gsusanj** [comment]
I am confirming, this issue is resolved, thank you!
