### ISSUE TITLE
How to create new label 

### ISSUE THREAD

**Issue by ivl04** [statikbe/laravel-filament-chained-translation-manager#39]
I want to create new label and store it in database how can I achieve that?

**Comment by sten** [comment]
@ivl04 We do not support that on purpose. Such a feature would allow a content editor to add new translation keys that would not be used by the application, resulting in confusion for developer and content editor. We see the translation manager as a tool for content editors and translators. Devs add translation keys in the php or json files.

If this really is a feature that you need, PRs are welcome if we can enable/disable it in the config.
